title: 박소연의 블로그
description: 새로 만들어 보았습니다.
baseurl: "" # 사용자 페이지이므로 비워둡니다
url: "https://SYeonHi.github.io" # 블로그 주소
permalink: /:categories/:title

content_type: Knowledge Base # 사이트 유형 설정
use_authors: true # 게시물 작성자 표시 여부

brand_logo: # 브랜드 로고 이미지 경로 (필요시)
brand_name: # 브랜드 이름 (필요시)
header: SYeonHi의 블로그에 오신 것을 환영합니다.
subheader: 프로젝트, 스터디 기록을 위주로 합니다.

meta_image: # 메타 이미지 경로 (필요시)

# 소셜 링크
twitter_username: # 트위터 사용자 이름 (필요시)
facebook_page: # 페이스북 페이지 URL (필요시)
github_username: SYeonHi # GitHub 사용자 이름
email: soyeon0964@chungbuk.ac.kr # 이메일 주소
linkedin_page: # LinkedIn 페이지 URL (필요시)
instagram_username: soyeon0964 # 인스타그램 사용자 이름 (필요시)

# 네비게이션 설정
nav_item_one: Github
nav_item_one_link: https://github.com/TeaGuns/odin

nav_item_two: Twitter
nav_item_two_link: https://twitter.com/TheTeaGuns

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Odin Home
nav_button_link: https://teaguns.github.io/odin/

# 추가 도움말 설정
help_one_title: Odin Bugs
help_one_content: If you find any bugs or problems with this theme, please open an issue over on Github.
help_one_button: Github
help_one_link: https://github.com/TeaGuns/odin/issues

help_two_title: Twitter
help_two_content: Feel free to tweet at me if you have suggestions for Odin. Or if you just want to say hi.
help_two_button: Twitter
help_two_link: https://twitter.com/theteaguns

# 빌드 설정
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# 처리에서 제외할 항목
exclude: # 필요시 항목 추가

# SASS 설정
sass:
  sass_dir: _scss
  style: :compressed
